spring:
  application:
    name: jokes-api
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jokes
    username:
    password:
  jpa:
    database-platform:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  security:
    user:
      password: possword